### ISSUE TITLE
Unindexed runs do not produce Undetermined.fastq.gz, but snakemake expects them

### ISSUE THREAD

**Issue by messersc** [bihealth/digestiflow-demux#12]
# Bug

Lanes without index reads to not produce Undetermined reads, as all reads belong to the one sample loaded.

```Undetermined_*’: No such file or directory```

# Fix

In case of now index reads configured (no B in bases mask), do not expect Undetermined* output files.

Should be fixed together with https://github.com/bihealth/digestiflow-demux/issues/10

**Comment by messersc** [comment]
@holtgrewe 

Fixed in the bcl2fastq2 wrapper, which does not try do copy non-existing `Undetermined*` files anymore.

Fixed in the snakemake workflow for flow cells with no index read.

Not fixed for flow cells with *perfect* index reads.

**Comment by holtgrewe** [comment]
Fixed in current master.
