### ISSUE TITLE
Add parameter to keep even qc failed reads

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/digestiflow-demux#14]
Important for tutorial where `TTTTTTTTT` would be filtered as it's an artifact...

**Comment by holtgrewe** [comment]
`--with-failed-reads` for bcl2fastq2

**Comment by messersc** [comment]
Should that also be a field in digestiflow-server? Or just a parameter for demux?

**Comment by holtgrewe** [comment]
Only cubi-demux as it's only useful for the tutorial ;)
