### ISSUE TITLE
Handling of runs with UMIs

### ISSUE THREAD

**Issue by messersc** [bihealth/digestiflow-demux#2]
To me, it looks like there is no good and robust way to decide if a run is dual barcode or barcode + UMI from the flowcell info.

Current test case is https://flowcells.bihealth.org/flowcells/22875de2-0f5f-42f6-84ec-5eb085f6c02f/flowcell/a988e5e7-48db-4902-ad82-5d3e13f642ec/

I changed the `current_reads` from `126T8B10B126T` to `126T8B10M126T` - 10B to 10M. Demultiplexing with picard yields R1, R2, barcode_1 and index_1 files.

How should we handle this in general? Do you think this one manual intervention is necessary?

**Comment by holtgrewe** [comment]
We will introduce an additional field in `digestiflow-web` for overriding this.

**Comment by holtgrewe** [comment]
Added `demux_reads` to override `planned_reads`
