### ISSUE TITLE
Support for per-library (or lane) bases masks

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/digestiflow-demux#4]
Here, we will have to split demultiplexing per read configuration.

Users should be able to override this per lane and per library in the Web UI. Only once it has been implemented there, should it be tackled here.

**Comment by messersc** [comment]
This can be done with bcl2fastq by writing a sample sheet for each configuration and then passing the corresponding bases mask to bcl2fastq2. Parallelization is possible through snakemake.

The only problem I could not find a solution for yet is with the Undetermined read files. Suppose you have to use different bases masks for a lane, you will end up with more than one fastq file for the Undetermined reads. Worse, each of these files will contain all reads belonging to all the samples demultiplexed with the other bases mask. I suppose the correct way would be to only keep the intersection of all Undetermined reads for each lane.

Thoughts?

**Comment by holtgrewe** [comment]
In this case, we will discard the undetermined reads. Users can get this information from the Digestiflow Web UI.
